

mod_id=nutsandfruit
curse_id=444242
curse_slug=nuts-and-fruit
mod_version=1.0.2
mod_name=nutsandfruit
mod_group_id=com.lothrazar.nutsandfruit
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=


flib_version=0.2.0
flib_file=8117455
